### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by WwWxQxQ** [CrazyHZM/understanding-the-principle-and-implementation-of-rpc-framework-samples#1]
# 2021年10月第1版 p13

1.5.4 RPC通信者
引用的下一行：大致意思是说【RCPCRuntime】负责

还有一个问题想要请教一下： p7 消息队列第三行：信号量是一个【计时器】，这个如果类比为JUC的Semaphore的话，是不是应该是【计数器】
XD

**Comment by CrazyHZM** [comment]
感谢提交勘误，已经收到。
在后续印刷的版本中将会改进。
@WWWWWWWXQ
